# Generated by Django 5.1.4 on 2025-01-14 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pslmatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='psl/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PZ', 'PESHAWAR ZALMI'), ('LQ', 'LAHORE QALANDARS'), ('KK', 'KARACHI KINGS'), ('QG', 'QUETTA GLADIATOR'), ('MS', 'MULTAN SULTAN')], max_length=2)),
            ],
        ),
    ]
