# Generated by Django 5.1.4 on 2025-01-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pslmatches',
            name='descriptions',
            field=models.TextField(default=''),
        ),
    ]
